### ISSUE TITLE
Meetup groups on Locations page

### ISSUE THREAD

**Issue by helenst** [pyladies/pyladies#138]
Some meetup groups do not appear to exist:
Nashville http://www.meetup.com/Nashville-PyLadies
Charleston http://www.meetup.com/PyLadies-Charleston/
Vancouver http://www.meetup.com/pyladiesvan/

Groups for Seoul and Salt Lake exist but are not linked from this page.
http://www.meetup.com/Seoul-PyLadies-Meetup/
http://www.meetup.com/Salt-Lake-Pyladies/

**Comment by econchick** [comment]
I can take down the info of the defunct locations, but with regards to the groups not listed, it's usually on the hands of the local organizers to submit a pull request.

TBH I'd like this information to easily come from a config.yaml file (probably the same one that you used in your PR).  So that I can just easily add a new link to a config file rather than mess with HTML.

**Comment by helenst** [comment]
ah, makes sense. I just saw some groups that were in the meetup list and not in Locations, and vice versa. And yes, it would be nice to have the meetup URL fragments, twitter IDs etc. in the yaml to generate the locations page content.
