### ISSUE TITLE
Onboarding new chapter?

### ISSUE THREAD

**Issue by Mariatta** [pyladies/pyladies#396]
In info@pyladies.com mailbox, we receive numerous inquiries related to starting new chapter, or people wondering if a chapter is active/inactive.

I feel like I don't have adequate information on how to respond/help with this type of questions.

1. Where should I forward the email to, if people had questions about starting their new chapter?

2. Regarding inquiries about local chapter, is there a full list of all chapter's email address (not personal organizer's email address, but actual `<city>@pyladies.com` email address? It would help us direct inquiries about local chapters.

**Comment by Mariatta** [comment]
Just reading prospective pyladies organizers kit: http://kit.pyladies.com/en/latest/prospective/index.html. It says:
- fill in the interest form
- wait for reply
- ping info@pyladies.com if no reply after a week.

I'm starting to co-handle info@pyladies.com, but I don't actually know what to do next after the ping? 😬

**Comment by econchick** [comment]
Hey @Mariatta - here's the process on my end:

1. Review the request content
    a. If there's already a PyLadies location of the request (or otherwise would share a lot of overlap), I email the submitter (and those that they include as co-organizers) if they know of the existing PyLadies location, or if they're effectively taking over / rebooting the location.
    b. Read the "How did you hear about PyLadies" and "What do you currently do with Python" as a simple pass for spam/trolls (never have had one, but just in case).
2. If all otherwise looks good, I create the user account (with the desired short name) in admin.google.com. If they're taking over a location, then I reset the password. In either case, I require a password reset on first login, and select the ability to send the initial login information via email to the submitter. But before I actually _send_ that initial login info, I do the next step.
3. Send the welcome email to the submitter plus any co-organizers they've named, and cc @lorenanicole (for my accountability and to help respond if there are any follow up questions). Email template below.
4. Then I send the login information. While maintaining the order of emails sent isn't needed, I like to make sure they receive the initial email before the login email for context. ¯\\_(ツ)_/¯

---
_Template:_

Hi `{{names}}`!

We’re so excited that you’re wanting to start a PyLadies in `{{location}}`!!

I've created "`{{shortname}}`@pyladies.com" email, so expect an email (to your personal email address, `{{submitter name}}`) within a few minutes on setting up your PyLadies account (http://www.google.com/a/pyladies.com). You'll need to reset the password when you first login **within 48 hours**.  Then go ahead and sign up for any accounts for PyLadies that you need with this new email (e.g. Meetup, Twitter, etc) - or update the accounts with this one.

Once done with signing up for everything, please complete the part II of the checklist [1].

To get `{{location}}` listed under `http://www.pyladies.com/locations/`, please make a pull request to `github.com/pyladies/pyladies`.  You just need to edit the `config.yml` file under the `www` directory.  More instructions are here [2].

When you want your own site, you can either create a static/all client-side site within the repo itself (like you see with others) and submit a pull request, or if you want it to have server side logic (like a Flask/Django app or something), then we can deploy it on Heroku (just let me know).  There are more instructions here [3], but let me know if you have any questions with this.

Please do *not* buy any domains - all domains are managed by PyLadies and the Python Software Foundation.  We'll be able to setup “`{{shortname}}`.pyladies.com” or something similar when you're ready.

If you have any other questions, don't hesitate to ask me or Lorena (cc'ed).

Welcome!

[1] http://kit.pyladies.com/en/latest/prospective/index.html#process-checklist
[2] http://kit.pyladies.com/en/latest/organizer/website/global.html#adding-your-location
[3] http://kit.pyladies.com/en/latest/organizer/website/local.html
