### ISSUE TITLE
Hopefully the final attempt to migrate the PyLadies static website

### ISSUE THREAD

**Issue by Cheukting** [pyladies/pyladies#649]
As per talking with @Mariatta there were several attmpt to migrate the PyLadies static website out from the previous one. There are some issues that can be addressed with a new website using a new flamework:
- Mynt is unmaintained and is causing lot of local build problem with Python >=3.8, it is locking us to use EoL verions of Python for deployment
- Some of the wigids with X (formarly Twitter) is not working
- "UPCOMING MEETUPS" is not showing anything since the chapters has been migrated

Therefore we suggest the following:

- build a modenize version with Hugo, the choice of Hugo is discussed and agreed by several PyLadies leaders in Slack. It is also suported by Netlify
- Keep it as close to the original as possible but remove the following:
  - link with Twitter as the community is now have a mix use of social media platforms
  - link with upcomming meetup as chapters is no longer posting updates
  - "location" page, instaed it should be redirected to a dynammic site to manage membership and chapters
  
  I have made a [mock up preview](https://dainty-arithmetic-d91235.netlify.app/) of the new website [here at this repo](https://github.com/Cheukting/pyladies-new-website).
  
As you can see except the above points it has keep close to the original as possible.
 
For the next step, I would suggest putting my preview repo into a new repo under PyLadies GH account, with all the README.md and CONTRIBUTING.md and licenses added back in. 

The reason of starting new is that the framework of Hugo and Mynt is very different and it is hard to compare like to like. Also we would like to keep the information of the chapters (which are suppoesed to be migrates) in the old repo for future reference. Once the migration is finish the old repo can be achieved for future reference.

Another option is to keep a clone repo of the old repo before over writing with the new website repo. That way the old issues and CI can be kept the same.

I am up for suggestions and comments, please feel free to suggest changes.

**Comment by Mariatta** [comment]
@pyladies/tech-and-infra-admins to review and provide feedback

**Comment by Cheukting** [comment]
I have also just put back the location page without individual chapter pages, all the links to chpater website and social medias are external links

**Comment by willingc** [comment]
Beautiful! I say ship it, and we can reformulate the location page in a separate PR! Thank you @Cheukting for doing this. I thought about bringing this up again after reading the post that Nati put together and thinking that we could make it so much easier to read.

**Comment by willingc** [comment]
Having tried to rewrite the old repo in the past. I think starting this as a new repo makes sense. We can use READMEs in subdirectories of the old repo to indicate when/if things have been migrated to the new repo.

**Comment by Mariatta** [comment]
Thanks @willingc Creating a new repo is easy, but since we have a whole bunch of process tied to this repository, I'm worried things will break (and will create some downtime to the website).

How about this:
- keep it in the same repository (pyladies/pyladies)
- rename the current main branch to "archived"
- add everything that Cheuk has done to the new "main" branch, and delete everything else as if starting new (the diff will look messy with probably 1000s removed files, but it's ok. We can fallback to the "archived" branch to look up things.)

This way I think in theory, we will get to the hookups like netlify, domain name, etc to the repo.

**Comment by BethanyG** [comment]
@Mariatta @willingc  -- Lynn and the rest of the council would like some time to review this, and think things over.
Could you pause please before re-arranging things in the repo or pushing anything live?  _Many thanks!_

**Comment by willingc** [comment]
@Mariatta That makes sense. Do whatever makes sense and introduces the least risk after getting the go ahead from @econchick and the rest of the council.

**Comment by Mariatta** [comment]
Thank you.

I do hope we can get some decisions and action surrounding this sooner than later.
In case people forgot, it has been almost 10 years since it was first brought up to [replace mynt](https://github.com/pyladies/pyladies/issues/161). 
And there has been another attempt at [modernizing the website](https://github.com/pyladies/pyladies/issues/482), which languished (and I recognize that the pandemic put pause on a lot of things).
Now that we have interested parties with time available, let's keep the momentum and conversation going.

The sooner we can make the website more maintainable, the easier it will be for contributors to contribute to the content and blog of PyLadies.

**Comment by Cheukting** [comment]
Thank you for bring this to the April meeting @econchick please kindly let me know if there's any follow up actions that need help.

**Comment by trallard** [comment]
Hey @Cheukting and et al. 👋🏽 

First, thanks for your enthusiasm and willingness to contribute to [improving our PyLadies website](https://github.com/pyladies/pyladies/issues/649).  This is a well-overdue improvement, and we know it was a lot of work (we are sorry it has been so frustrating). 

However, while discussing this project, we –the global council– agreed that we would like this website migration to be a participatory process involving multiple members of the PyLadies community to ensure a) we are meeting their needs and b) we have a plan for its implementation and long-term maintenance, and c) that this becomes an opportunity for a wide range of PyLadies to get involved in designing, coding, and creating content.  

It's been 12 years since the original website design and 13 years since PyLadies was founded.  Rather than rush to replicate what we currently have on a more modern tech stack, we'd like to pause and rethink/redesign the site from the ground up to reflect where we are today as an organization. To that effect, we plan to:
1. Work on a requirements/specification document before any implementation
1. Convene during the first day of PyCon Sprints to have a discussion about the PyLadies website and requirements
1. Work with a UX designer to revamp the site
1. Organize a series of sprints/hackathons to work collectively on the website

This means that while we appreciate and recognise your effort, we will not be merging your PR. Instead, we’d like to invite you to participate in the abovementioned process. We'd like to make building out the new site a fun and meaningful path to both first-time and veteran open-source contributions. We know all of this is going to take time and might be messy, but we also think that it is a process that is well worth going through.

**Comment by willingc** [comment]
I have a suggestion to make Point 1 more concrete. Would it be possible to create a new `pyladies-site-2024` repo? We could then use that repo to focus discussions and issues for a modernized site. We could also move over the static assets and contents (not the whole build toolchain) so that new ideas/prototypes could be done on branches and not disrupt the existing site.

Benefits: 
- Open planning
- Prototyping
- Good separation of content from display/build tooling
- Milestone could be set (or projects) for next steps (perhaps working in 3 month goals)

**Comment by Cheukting** [comment]
It's ok @trallard , it was fun to create this PR. Let me know if you want any help in the future. Shall I close it for now?

**Comment by trallard** [comment]
Thanks for the suggestion @willingc agree that having a separate repo for iteration and discussions would be very helpful and encourage participation and feedback from community members, perhaps this can be a concrete first deliverable for this upcoming sprint. 
That said it would be great having you and @Cheukting join us during PyCon to get this off the ground.

@Cheukting for now, let's close this PR.
